language: go
before_install:
 - wget https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_darwin_amd64-1.9.6.zip
 - unzip -d $HOME go_appengine_sdk_linux_amd64-1.9.6.zip
 - ln -s $HOME/go_appengine/goroot/src/pkg/appengine $HOME/gopath/src/appengine
 - ln -s $HOME/go_appengine/goroot/src/pkg/appengine_internal $HOME/gopath/src/appengine_internal
 - export PATH=$PATH:$HOME/go_appengine
install: go get github.com/qedus/nds
script: go test
